### ISSUE TITLE
"Bring to front" messes up the window order

### ISSUE THREAD

**Issue by imiric** [romeshell/windows-alt-tab#6]
I really love the "Bring to front" feature, but unfortunately it breaks the window order that makes quickly switching between two windows impossible.

With the option turned on, it seems Mutter actually registers a switch to that window, even if you don't release Alt-Tab with this extension.

For example, say you have several Chrome windows and a terminal open. You're inside a specific Chrome window and want to switch to the terminal. You Alt-Tab to it with the "Bring to front" feature active and step over several windows on the way. When you get to the terminal, you release Alt. Then, you want to switch back to the same Chrome window. But now, instead of Alt-Tab taking you directly to it, it takes you to the last window you crossed before switching to the terminal. This makes you have to hunt for the window in the Alt-Tab list, and then do the same thing to switch back to the terminal. This pretty much kills the main benefit of Alt-Tab.

However, with "Selected Window Display" set to "None", quickly Alt-Tabbing does what you'd expect.

Thanks for the great extension!

**Comment by kroylar** [comment]
I agree. This is a rather unfortunate side effect of having "Bring To Front" selected.

What should happen is that windows are shown to you as you alt-tab through them, but then sent back to their current place in the stack. The only thing that actually changes a window's position in the stack is to actually select it by either releasing alt or by clicking with the mouse.

**Comment by tglman** [comment]
i understood the problem but is a bit hard to fix.
the cause is this call: Main.activateWindow(app.cachedWindows[0]); 
here:
https://github.com/romeshell/windows-alt-tab/blob/master/windows-alt-tab%40tglman.org/extension.js#L342

i think a way to fix it is take a preview of window and don't use the original window
an example how take a preview of window is here (until line 267):
https://github.com/romeshell/windows-alt-tab/blob/master/windows-alt-tab%40tglman.org/extension.js#L261

and after took the preview we need "just" to show it ... but i don't have and example now ;)

now i'm a bit busy, so i don't know when i can try to fix it ... so if you want you can just try to patch it ;)

Tnks!!!

**Comment by kroylar** [comment]
I took a quick look yesterday and noticed the same thing.  I'm not at all familiar with the new gnome. Were is Main.activateWindow defined? Is there an API reference somewhere that I can look at?

**Comment by tglman** [comment]
the api ... i don't know ... i usually look at the js code, and this code is usually located here: /usr/share/gnome-shell/js/ui but depend on your distribution, the code of activateWindow is in:/usr/share/gnome-shell/js/ui/main.js at line 821 but it just call mutter ... 
Maybe you can try to create a clone of window image, create a new ClutterActor e push the image of window in the original position .. and if selected just delete it and activate the real window....

so ... is complex ... but i think is a good chance to play with the shell ;)

**Comment by tglman** [comment]
better later than naver, tested on gnome-shell 3.4 let me reopen it if there are issues with other versions.

**Comment by imiric** [comment]
Great, thanks! Unfortunately, I moved on from Gnome, but this is probably one of the most used extensions out there, so kudos for maintaining it!
