### ISSUE TITLE
GNOME 3.8 support

### ISSUE THREAD

**Issue by gregkh** [romeshell/windows-alt-tab#9]
This extension doesn't seem to work for GNOME 3.8.  I've tried the "simple" thing and just added the version number to the prefs.js file, which enables it, but the behavior of alt-tab is not modified.

**Comment by gregkh** [comment]
Sorry, that was metadata.json that I edited, not prefs.js.

**Comment by tglman** [comment]
tnks for the segnalation, actually i didn't test it until now in GNOME 3.8, i'll test and fix it early possible, but i don't think i can provide an fixed version before a couple of week

**Comment by orschiro** [comment]
Could you then please describe what we need to do to make it compatible?

Thanks!

**Comment by tglman** [comment]
hi, actually i don't know, because i don't have anymore  a test environment (the motherboard of my laptop is burned), i hope to be back working early possible, but if you want you can give me the error logs, and maybe we can work together for fix it! you can start from this: http://mathematicalcoffee.blogspot.co.uk/2012/09/gnome-shell-extensions-getting-started.html  

also for catch the log rerun the gnome shell from a console using

gnome-shell --replace

and also press ALT+F2 after write "lg" and go to the tab extensions there will be displayed some errors!

tnks!!

if you want you can also contact directly me using jabber.org my username is tglman ;)

**Comment by orschiro** [comment]
I adapted metadata.json to reflect 3.8 and indeed it still seems to be compatible.

No need for further adaption. :)

EDIT:

Sorry, it is not working completely. Though it does not complain about any error (no error log in lg), windows are grouped together.

**Comment by gagalago** [comment]
same for me, no errors but i can still switch from windows in different workspaces.

**Comment by tglman** [comment]
slowly i'm working on!

**Comment by gagalago** [comment]
there is now an official plugin that does the job
https://git.gnome.org/browse/gnome-shell-extensions/tree/extensions/alternate-tab

you can perhaps inspire you

**Comment by tglman** [comment]
thank you for the suggestion, i'll try it! maybe already cover my uses cases and i can stop to duplicate code ;) maybe no ...  and i'll still continue to develop mine ..... i'll see and let you know!
